<?php
/* This file was generated by the install process. You can edit it. Please see config.original.php to understand the configuration items. */
$cfg['web_root'] = 'https://example.onion/';
$cfg['var_root'] = '/www/storage-jirafeau@usb/';
$cfg['lang'] = 'en';
$cfg['style'] = 'courgette';
$cfg['preview'] = true;
$cfg['enable_crypt'] = false;
$cfg['link_name_length'] = 20;
$cfg['upload_password'] = array ();
$cfg['upload_ip'] = array ();
$cfg['admin_password'] = '';
$cfg['admin_http_auth_user'] = '';
$cfg['availabilities'] = array (  'minute' => true,  'hour' => true,  'day' => true,  'week' => true,  'month' => true,  'year' => false,  'none' => false,);
$cfg['maximal_upload_size'] = 0;
$cfg['proxy_ip'] = array ();
$cfg['installation_done'] = true;
?>
