#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
#PROCD_DEBUG=1
CMD=$(cat /etc/wm/wmd_cmd)

start_service() {

	procd_open_instance
	procd_set_param command $CMD
    procd_set_param file /etc/wm/wmd_cmd # /etc/init.d/wmd reload will restart the daemon if these file has changed
	#procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
  #  procd_set_param stdout 1 # forward stdout of the command to logd
  #  procd_set_param stderr 1 # same for stderr
  #  procd_set_param user nobody # run service as user nobody
    procd_close_instance 
}

reload_service() {
	stop
    start
}

stop_service() {
    
    # Kill all $CMD 
    kill -9 $(ps | grep "$CMD" | awk -F ' ' '{printf "%s ", $1}')  >/dev/null 2>&1
    /usr/bin/wm purge # Purges all configurations
    /usr/bin/wm disable # Disables wifi manager
}
