#!/bin/bash
set -e

# Copy the autogenerated keys to the output directory.
mkdir -p "${OUTPUT_DIR}/keys/uhttpd"
mkdir -p "${OUTPUT_DIR}/keys/ca"
mkdir -p "${OUTPUT_DIR}/keys/tor"
cp -r -- ./files/etc/tor/lib/hidden_service/jirafeau/ "${OUTPUT_DIR}/keys/tor/"
cp -- ./files/etc/uhttpd.* "${OUTPUT_DIR}/keys/uhttpd/"

# Copy the root certificates as well.
PROFILE_DIR="${PROFILE_DIR}" /OUTSIDE/script/guest/copy_ssl_root_cert.sh "${OUTPUT_DIR}/keys/ca/"
