#!/bin/bash
set -e

# Copy the autogenerated keys to the output directory.
mkdir -p "${OUTPUT_DIR}/keys/uhttpd"
mkdir -p "${OUTPUT_DIR}/keys/ca"
cp -r -- ./files/etc/tor/lib/hidden_service/WEBtor/ "${OUTPUT_DIR}/keys/"
cp -- ./files/etc/uhttpd.* "${OUTPUT_DIR}/keys/uhttpd/"

# Copy the root certificates as well.
/vagrant/script/guest/copy_ssl_root_cert.sh "${OUTPUT_DIR}/keys/ca/"
