#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

# OpenWrt HappyHacker patch:
#   This file has been modified to always launch the telnet server, no matter what.
#   Useful for debugging, but absolutely discouraged in production!

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -F -l /bin/login.sh
	procd_close_instance
}
