#!/bin/sh /etc/rc.common
# This is an OpenWrt HappyHacker patch.

START=40

start() {

	# Automount the MicroSD card.
	/sbin/block detect | sed "s/enabled\t'0'/enabled\t'1'/g" > /etc/config/fstab
	/sbin/block mount

	# Apply the MicroSD card filesystem changes.
	/etc/sdcard_fixes.sh

}

stop() {
	/sbin/block umount
}
