#!/bin/sh

mkdir -p /mnt/sda1/jirafeau/files
mkdir -p /mnt/sda1/jirafeau/links
mkdir -p /mnt/sda1/jirafeau/async
mkdir -p /mnt/sda1/jirafeau/alias
mkdir -p /mnt/sda1/jirafeau/static
mkdir -p /mnt/sda1/tmp/jirafeau

chmod 777 -R /mnt/sda1/tmp/
chmod 766 -R /mnt/sda1/jirafeau/
chmod 755 -R /www/jirafeau/

exit 0

